### PR TITLE
Update course api to get location info

### PR DESCRIPTION
**Pull request by JustinKnueppel**

### CODE REVIEW

**Comment by JustinKnueppel** [comment]
Closes #9

**Comment by JustinKnueppel** [comment]
This PR lost its scope a bit, but now has a lot of changes to make the structure of the yaml file easier to work with and fixed several errors

**Comment by seanmesserly** [comment]
Couple general comments:

1.  No password is sent for user creation. Are we just doing password-less magic links to sign in?
2. We use course ID's in our requests, but layout names (i.e. create new score card endpoint). What was the rationale between the layouts using strings instead of ID's?
3. Kind of goes with first, but presumably some (or most) of these routes will require authentication first. Is there a way to mark them as such?

**Comment by JustinKnueppel** [comment]
> Couple general comments:
> 
> 1.  No password is sent for user creation. Are we just doing password-less magic links to sign in?
> 2. We use course ID's in our requests, but layout names (i.e. create new score card endpoint). What was the rationale between the layouts using strings instead of ID's?
> 3. Kind of goes with first, but presumably some (or most) of these routes will require authentication first. Is there a way to mark them as such?

For 1, I've been building up the API/docs incrementally to try to get functionality first and then we can add in authentication and restrictive access to routes and all that jazz.

For 2, this was a limitation of the initial routes we laid out as we didn't nest far down enough to have layout IDs, and names are unique anyways for a given course. However in the issue I created earlier i proposed new routes which would end up making us use layout IDs instead of names for that very reason that it's inconsistent. But to make it work for this version of the API I had started with names.

For 3, yes there is support for showing authentication methods in the OpenAPI spec that we can explore! I believe it will show both how to authenticate as well as which routes accept which authentication methods

**Pull request merged**
